apiVersion: v1
kind: Service
metadata:
  name: contoso-ship-manager-frontend
  namespace: default
spec:
  selector:
    app: contoso-ship-manager-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contoso-ship-manager-frontend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: contoso-ship-manager.6a51a54fce694d2da974.eastasia.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contoso-ship-manager-frontend
                port: 
                  name: http